name: build-openldap

services:
  openldap:
    build:
      context: openldap
      dockerfile: Dockerfile
      args:
        - ENABLE_MEMBEROF=no
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
#    volumes:
#      - ./data:/var/openldap-data
    env_file: .env